[package]
name = "p2"
version = "0.1.0"
authors = ["Leandro Coutinho <lescoutinhovr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"

[build-dependencies]
# cmake = "0.1.44"

